### ISSUE TITLE
Patch for new ocaml versions

### ISSUE THREAD

**Issue by ulrikstrid** [esy-ocaml/ocaml#36]
This is not a issue, but if anyone wants to patch new versions this is a very simple way:
Take the content of this gist and put it in `esy-patch.patch`
https://gist.github.com/ulrikstrid/a4f0058e0153e3317fae44d1792bddb4

Checkout the wanted tag `git checkout 4.11.0` and then create a new branch from it `git checkout -b 4.11.0+esy`.
Then run `git apply esy-patch.patch`.
Commit and push.

**Comment by ManasJayanth** [comment]
This is really cool. Let's use if for 4.11. I think we should check in this patch and mention it in the README

**Comment by ulrikstrid** [comment]
Thanks for incorporating this into the readme @prometheansacrifice, I'll close this issue now
